apiVersion: v1
kind: Service
metadata:
  labels:
    id: cross-server-ready
  name: service-am-i-ready
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    id: cross-server-ready
